### ISSUE TITLE
How to handle multiple references to files?

### ISSUE THREAD

**Issue by jt196** [derwish-pro/obsidian-consistent-attachments-and-links#13]
I'm assuming you have thought about this but the reorganisation of attachments from a link reference can be a bit problematic if the file is referenced in 2 places. Is there something in the settings to account for conflicts? 

Had a little accident with the [find unlinked files](https://github.com/Vinzent03/find-unlinked-files#move-files-with-certain-extension-in-output-file-to-system-trash-extra-command) script moving all the resources it mentions to the root folder before I realised I had to ignore the file!

**Comment by derwish-pro** [comment]
The idea behind the plugin is to put all attachments in the same folder with the note. To minimize the risk of any possible conflict, I recommend using this plugin in conjunction with my other plugin - https://github.com/derwish-pro/obsidian-unique-attachments. The unique-attachments plugin ensures that two attachments with the same content will have the same name. Accordingly, two files with different content will have different names. The name is generated based on the content of the file using a hash function. 

Thus, if two notes that are in the same folder have a link to one file, then the file will be one: 
folder1\note1.md (it uses attachments\image.png)
folder1\note2.md (it uses attachments\image.png)
folder1\attachments\image.png

If notes in two different folders referred to the same file, then the plugin will copy this file: 
folder1\note1.md (it uses attachments\image.png)
folder1\attachments\image.png
folder2\note2.md (it uses attachments\image.png)
folder2\attachments\image.png

**Comment by derwish-pro** [comment]
The plugin has a setting "Delete duplicate attachments while note moving". I recommend enabling it if you are using unique-attachments plugin, or disable it if not. 
If this option is enabled, the plugin will automatically delete a file with the same name if several copies of it are copied into one folder with attachments (which is convenient when you know that two files with the same name are exactly two copies of the file with the same content). If the option is disabled, the plugin will never delete files in case of conflicts.

**Comment by jt196** [comment]
Thanks for this info, just moving notes from Joplin which manages all this for you, so some extra considerations for the extra freedom. Will look into the Unique Attachments plugin then.
